"""Demo seed data mirroring packages/shared/src/seedData.ts.

Changes here must be mirrored there (the web login page lists the demo
accounts from the TypeScript copy)."""

DEMO_PASSWORD = 'gctc-demo'

DEMO_USERS = [
    {
        'id': 'buyer-1',
        'name': 'Aarav Mehta',
        'email': 'buyer@gctc.demo',
        'role': 'buyer',
        'organization': 'Mehta Retail Procurement',
        'demo_password': DEMO_PASSWORD,
    },
    {
        'id': 'seller-1',
        'name': 'Verified Supplier Desk',
        'email': 'seller@gctc.demo',
        'role': 'seller',
        'organization': 'GCTC Supplier Network',
        'demo_password': DEMO_PASSWORD,
    },
    {
        'id': 'admin-1',
        'name': 'Operations Admin',
        'email': 'admin@gctc.demo',
        'role': 'admin',
        'organization': 'Global Chamber of Trade and Commerce',
        'demo_password': DEMO_PASSWORD,
    },
    {
        'id': 'seller-2',
        'name': 'Deccan Spice Supply',
        'email': 'seller-2@gctc.internal',
        'role': 'seller',
        'organization': 'GCTC Supplier Network',
    },
    {
        'id': 'seller-3',
        'name': 'Idukki Grower Collective',
        'email': 'seller-3@gctc.internal',
        'role': 'seller',
        'organization': 'GCTC Supplier Network',
    },
    {
        'id': 'seller-4',
        'name': 'Malnad Coffee Works',
        'email': 'seller-4@gctc.internal',
        'role': 'seller',
        'organization': 'GCTC Supplier Network',
    },
]

PRODUCT_SEEDS = [
    {
        'id': 'cashew-maharashtra',
        'seller_id': 'seller-1',
        'corridor_id': 'maharashtra-india',
        'product_class': 'food',
        'name': 'Premium cashew kernels W320',
        'category': 'Dry fruits',
        'state': 'Maharashtra',
        'origin': 'Ratnagiri verified processor cluster',
        'image_url': '/product-images/cashews.jpg',
        'unit': '500 kg wholesale lot',
        'base_price': 462000,
        'price_updated_at': '2026-06-28',
        'procurement_frequency': 'Monthly',
        'available_qty': '9 lots available',
        'specs': ['W320 grade', 'Vacuum-packed cartons', 'Kernel moisture below 5%'],
        'certifications': ['FSSAI licence verified', 'Batch quality report', 'GCTC supplier verification'],
        'decision_factors': ['Consistent wholesale grade', 'Retail-ready packing', 'Pan-India delivery available'],
        'note': 'Seller identity is protected. Buyers see verified origin, quality, availability, and the current GCTC offer.',
    },
    {
        'id': 'cocoa-andhra',
        'seller_id': 'seller-1',
        'corridor_id': 'andhra-pradesh-india',
        'product_class': 'food',
        'name': 'Natural cocoa powder',
        'category': 'Food ingredients',
        'state': 'Andhra Pradesh',
        'origin': 'West Godavari processing cluster',
        'image_url': '/product-images/cocoa.jpg',
        'unit': '1,000 kg wholesale lot',
        'base_price': 318000,
        'price_updated_at': '2026-06-24',
        'procurement_frequency': 'Fortnightly',
        'available_qty': '6 lots available',
        'specs': ['10-12% fat', 'Fine mesh powder', 'Food-grade paper sacks with liner'],
        'certifications': ['FSSAI licence verified', 'Batch COA', 'Food safety declaration'],
        'decision_factors': ['Suitable for bakeries and beverages', 'Stable repeat supply', 'Inspection report available'],
        'note': 'Suitable for bakeries, beverage mixes, institutional buyers, and private-label food production.',
    },
    {
        'id': 'sesame-gujarat',
        'seller_id': 'seller-1',
        'corridor_id': 'gujarat-india',
        'product_class': 'plant',
        'name': 'Hulled sesame seeds',
        'category': 'Seeds and grains',
        'state': 'Gujarat',
        'origin': 'Unjha aggregation and processing cluster',
        'image_url': '/product-images/sesame.jpg',
        'unit': '2,000 kg wholesale lot',
        'base_price': 286000,
        'price_updated_at': '2026-06-25',
        'procurement_frequency': 'Monthly',
        'available_qty': '7 lots available',
        'specs': ['99.95% purity', 'Hulled white sesame', '25 kg food-grade bags'],
        'certifications': ['FSSAI licence verified', 'Aflatoxin test', 'Purity report'],
        'decision_factors': ['Bulk supply available', 'Quality screened before dispatch', 'Oil and bakery grade'],
        'note': 'A verified bulk sesame listing for food processors, oil mills, bakeries, and institutional buyers.',
    },
    {
        'id': 'turmeric-telangana',
        'seller_id': 'seller-2',
        'corridor_id': 'telangana-india',
        'product_class': 'food',
        'name': 'Single-origin turmeric powder',
        'category': 'Spices',
        'state': 'Telangana',
        'origin': 'Nizamabad spice processing cluster',
        'image_url': '/product-images/turmeric.jpg',
        'unit': '500 kg wholesale lot',
        'base_price': 185000,
        'price_updated_at': '2026-06-27',
        'procurement_frequency': 'Weekly',
        'available_qty': '8 lots this week',
        'specs': ['Curcumin 4.8%', 'Moisture below 8%', 'Food-grade laminated bulk packs'],
        'certifications': ['FSSAI licence verified', 'ISO 22000', 'Lab-tested batch COA'],
        'decision_factors': ['High curcumin density', 'Stable weekly supply', 'Traceable state origin'],
        'note': 'A lab-tested wholesale spice listing for food manufacturers, distributors, and retailers.',
    },
    {
        'id': 'millet-rajasthan',
        'seller_id': 'seller-2',
        'corridor_id': 'rajasthan-india',
        'product_class': 'plant',
        'name': 'Pearl millet grain',
        'category': 'Grains',
        'state': 'Rajasthan',
        'origin': 'Jodhpur farmer aggregation cluster',
        'image_url': '/product-images/millet.jpg',
        'unit': '2,000 kg wholesale lot',
        'base_price': 142000,
        'price_updated_at': '2026-06-21',
        'procurement_frequency': 'Weekly',
        'available_qty': '12 lots this week',
        'specs': ['Machine-cleaned grain', 'Moisture below 12%', '50 kg food-grade bags'],
        'certifications': ['FSSAI licence verified', 'Moisture report', 'GCTC lot inspection'],
        'decision_factors': ['Reliable bulk availability', 'Food-processing grade', 'Competitive interstate supply'],
        'note': 'Bulk pearl millet for food processors, flour mills, institutional kitchens, and distributors.',
    },
    {
        'id': 'cardamom-kerala',
        'seller_id': 'seller-3',
        'corridor_id': 'kerala-india',
        'product_class': 'plant',
        'name': 'Premium green cardamom',
        'category': 'Spices',
        'state': 'Kerala',
        'origin': 'Idukki verified grower aggregation',
        'image_url': '/product-images/cardamom.jpg',
        'unit': '120 kg wholesale lot',
        'base_price': 336000,
        'price_updated_at': '2026-06-26',
        'procurement_frequency': 'Fortnightly',
        'available_qty': '5 lots this week',
        'specs': ['7-8 mm bold grade', 'Low split percentage', 'Moisture-controlled cartons'],
        'certifications': ['Spices Board registration', 'FSSAI licence verified', 'Residue test report'],
        'decision_factors': ['Premium aroma retention', 'Strong quality traceability', 'Verified Idukki origin'],
        'note': 'Premium spice lots with verified grade, state origin, and quality documents.',
    },
    {
        'id': 'coffee-karnataka',
        'seller_id': 'seller-4',
        'corridor_id': 'karnataka-india',
        'product_class': 'plant',
        'name': 'Robusta coffee beans',
        'category': 'Coffee',
        'state': 'Karnataka',
        'origin': 'Chikkamagaluru coffee grower cluster',
        'image_url': '/product-images/coffee.jpg',
        'unit': '2,000 kg wholesale lot',
        'base_price': 408000,
        'price_updated_at': '2026-06-23',
        'procurement_frequency': 'Monthly',
        'available_qty': '4 lots this week',
        'specs': ['Screen 16', 'Moisture 11-12%', 'Jute bags with food-grade liner'],
        'certifications': ['Coffee Board registration', 'Quality inspection report', 'GCTC supplier verification'],
        'decision_factors': ['Consistent blending grade', 'Scalable domestic supply', 'Traceable Karnataka origin'],
        'note': 'Reliable bulk coffee input for roasters, beverage manufacturers, and institutional buyers.',
    },
]

SELLER_SALE_SEEDS = [
    {
        'id': 'SALE-2048',
        'seller_id': 'seller-1',
        'product_id': 'cashew-maharashtra',
        'buyer_alias': 'Buyer account DL-184',
        'sold_at': '2026-06-24',
        'lots': 3,
        'quantity_tons': 1.5,
        'amount': 1386000,
        'fulfilment': 'turnkey',
        'quality_status': 'passed',
        'dispute_count': 0,
    },
    {
        'id': 'SALE-2036',
        'seller_id': 'seller-1',
        'product_id': 'cocoa-andhra',
        'buyer_alias': 'Buyer account MH-092',
        'sold_at': '2026-06-17',
        'lots': 2,
        'quantity_tons': 2,
        'amount': 636000,
        'fulfilment': 'sourcing-only',
        'quality_status': 'passed',
        'dispute_count': 0,
    },
    {
        'id': 'SALE-2019',
        'seller_id': 'seller-1',
        'product_id': 'sesame-gujarat',
        'buyer_alias': 'Buyer account KA-241',
        'sold_at': '2026-06-05',
        'lots': 1,
        'quantity_tons': 2,
        'amount': 286000,
        'fulfilment': 'turnkey',
        'quality_status': 'review',
        'dispute_count': 1,
    },
    {
        'id': 'SALE-1998',
        'seller_id': 'seller-2',
        'product_id': 'turmeric-telangana',
        'buyer_alias': 'Buyer account TN-033',
        'sold_at': '2026-05-28',
        'lots': 4,
        'quantity_tons': 2,
        'amount': 740000,
        'fulfilment': 'turnkey',
        'quality_status': 'passed',
        'dispute_count': 0,
    },
]

LOGISTICS_PARTNER_SEEDS = [
    {
        'id': 'LOG-WH-014',
        'type': 'Warehouse',
        'legal_name': 'Harbourline Storage Private Limited',
        'corridor': 'Mumbai, Maharashtra',
        'base_rate_per_ton': 1450,
        'distance_rate_per_ton_km': 0,
        'capacity': '2,400 tons',
        'status': 'Verified',
        'last_audit': '2026-05-12',
    },
    {
        'id': 'LOG-TR-027',
        'type': 'Truck',
        'legal_name': 'Western Freight Carriers',
        'corridor': 'Maharashtra, Gujarat, and Rajasthan',
        'base_rate_per_ton': 900,
        'distance_rate_per_ton_km': 4.2,
        'capacity': '18 trucks',
        'status': 'Verified',
        'last_audit': '2026-04-22',
    },
    {
        'id': 'LOG-CT-009',
        'type': 'Container trailer',
        'legal_name': 'Interstate Trailer Services',
        'corridor': 'West and South India',
        'base_rate_per_ton': 1250,
        'distance_rate_per_ton_km': 5.1,
        'capacity': '12 trailers',
        'status': 'Review due',
        'last_audit': '2025-12-18',
    },
    {
        'id': 'LOG-PM-031',
        'type': 'Packing and movers',
        'legal_name': 'CargoCare Handling LLP',
        'corridor': 'Pan India',
        'base_rate_per_ton': 2200,
        'distance_rate_per_ton_km': 1.3,
        'capacity': '32 crews',
        'status': 'Verified',
        'last_audit': '2026-05-30',
    },
    {
        'id': 'LOG-LD-044',
        'type': 'Local delivery',
        'legal_name': 'CityDock Delivery Network',
        'corridor': 'Delhi NCR, Mumbai MMR, Bengaluru, and Chennai',
        'base_rate_per_ton': 700,
        'distance_rate_per_ton_km': 3.8,
        'capacity': 'Same-day under 8 tons',
        'status': 'Verified',
        'last_audit': '2026-06-03',
    },
]
