import type { LogisticsPartnerSeed, ProductSeed, Role, SellerSaleSeed } from './types.ts'

export interface DemoUserSeed {
  id: string
  name: string
  email: string
  role: Role
  organization: string
  /** Only demo accounts get a known password; internal seller tenants stay locked. */
  demoPassword?: string
}

export const DEMO_PASSWORD = 'gctc-demo'

export const demoUsers: DemoUserSeed[] = [
  {
    id: 'buyer-1',
    name: 'Aarav Mehta',
    email: 'buyer@gctc.demo',
    role: 'buyer',
    organization: 'Mehta Retail Procurement',
    demoPassword: DEMO_PASSWORD,
  },
  {
    id: 'seller-1',
    name: 'Verified Supplier Desk',
    email: 'seller@gctc.demo',
    role: 'seller',
    organization: 'GCTC Supplier Network',
    demoPassword: DEMO_PASSWORD,
  },
  {
    id: 'admin-1',
    name: 'Operations Admin',
    email: 'admin@gctc.demo',
    role: 'admin',
    organization: 'Global Chamber of Trade and Commerce',
    demoPassword: DEMO_PASSWORD,
  },
  {
    id: 'seller-2',
    name: 'Deccan Spice Supply',
    email: 'seller-2@gctc.internal',
    role: 'seller',
    organization: 'GCTC Supplier Network',
  },
  {
    id: 'seller-3',
    name: 'Idukki Grower Collective',
    email: 'seller-3@gctc.internal',
    role: 'seller',
    organization: 'GCTC Supplier Network',
  },
  {
    id: 'seller-4',
    name: 'Malnad Coffee Works',
    email: 'seller-4@gctc.internal',
    role: 'seller',
    organization: 'GCTC Supplier Network',
  },
]

export const productSeeds: ProductSeed[] = [
  {
    id: 'cashew-maharashtra',
    sellerId: 'seller-1',
    corridorId: 'maharashtra-india',
    productClass: 'food',
    name: 'Premium cashew kernels W320',
    category: 'Dry fruits',
    state: 'Maharashtra',
    origin: 'Ratnagiri verified processor cluster',
    imageUrl: '/product-images/cashews.jpg',
    unit: '500 kg wholesale lot',
    basePrice: 462000,
    priceUpdatedAt: '2026-06-28',
    procurementFrequency: 'Monthly',
    availableQty: '9 lots available',
    specs: ['W320 grade', 'Vacuum-packed cartons', 'Kernel moisture below 5%'],
    certifications: ['FSSAI licence verified', 'Batch quality report', 'GCTC supplier verification'],
    decisionFactors: ['Consistent wholesale grade', 'Retail-ready packing', 'Pan-India delivery available'],
    note: 'Seller identity is protected. Buyers see verified origin, quality, availability, and the current GCTC offer.',
  },
  {
    id: 'cocoa-andhra',
    sellerId: 'seller-1',
    corridorId: 'andhra-pradesh-india',
    productClass: 'food',
    name: 'Natural cocoa powder',
    category: 'Food ingredients',
    state: 'Andhra Pradesh',
    origin: 'West Godavari processing cluster',
    imageUrl: '/product-images/cocoa.jpg',
    unit: '1,000 kg wholesale lot',
    basePrice: 318000,
    priceUpdatedAt: '2026-06-24',
    procurementFrequency: 'Fortnightly',
    availableQty: '6 lots available',
    specs: ['10-12% fat', 'Fine mesh powder', 'Food-grade paper sacks with liner'],
    certifications: ['FSSAI licence verified', 'Batch COA', 'Food safety declaration'],
    decisionFactors: ['Suitable for bakeries and beverages', 'Stable repeat supply', 'Inspection report available'],
    note: 'Suitable for bakeries, beverage mixes, institutional buyers, and private-label food production.',
  },
  {
    id: 'sesame-gujarat',
    sellerId: 'seller-1',
    corridorId: 'gujarat-india',
    productClass: 'plant',
    name: 'Hulled sesame seeds',
    category: 'Seeds and grains',
    state: 'Gujarat',
    origin: 'Unjha aggregation and processing cluster',
    imageUrl: '/product-images/sesame.jpg',
    unit: '2,000 kg wholesale lot',
    basePrice: 286000,
    priceUpdatedAt: '2026-06-25',
    procurementFrequency: 'Monthly',
    availableQty: '7 lots available',
    specs: ['99.95% purity', 'Hulled white sesame', '25 kg food-grade bags'],
    certifications: ['FSSAI licence verified', 'Aflatoxin test', 'Purity report'],
    decisionFactors: ['Bulk supply available', 'Quality screened before dispatch', 'Oil and bakery grade'],
    note: 'A verified bulk sesame listing for food processors, oil mills, bakeries, and institutional buyers.',
  },
  {
    id: 'turmeric-telangana',
    sellerId: 'seller-2',
    corridorId: 'telangana-india',
    productClass: 'food',
    name: 'Single-origin turmeric powder',
    category: 'Spices',
    state: 'Telangana',
    origin: 'Nizamabad spice processing cluster',
    imageUrl: '/product-images/turmeric.jpg',
    unit: '500 kg wholesale lot',
    basePrice: 185000,
    priceUpdatedAt: '2026-06-27',
    procurementFrequency: 'Weekly',
    availableQty: '8 lots this week',
    specs: ['Curcumin 4.8%', 'Moisture below 8%', 'Food-grade laminated bulk packs'],
    certifications: ['FSSAI licence verified', 'ISO 22000', 'Lab-tested batch COA'],
    decisionFactors: ['High curcumin density', 'Stable weekly supply', 'Traceable state origin'],
    note: 'A lab-tested wholesale spice listing for food manufacturers, distributors, and retailers.',
  },
  {
    id: 'millet-rajasthan',
    sellerId: 'seller-2',
    corridorId: 'rajasthan-india',
    productClass: 'plant',
    name: 'Pearl millet grain',
    category: 'Grains',
    state: 'Rajasthan',
    origin: 'Jodhpur farmer aggregation cluster',
    imageUrl: '/product-images/millet.jpg',
    unit: '2,000 kg wholesale lot',
    basePrice: 142000,
    priceUpdatedAt: '2026-06-21',
    procurementFrequency: 'Weekly',
    availableQty: '12 lots this week',
    specs: ['Machine-cleaned grain', 'Moisture below 12%', '50 kg food-grade bags'],
    certifications: ['FSSAI licence verified', 'Moisture report', 'GCTC lot inspection'],
    decisionFactors: ['Reliable bulk availability', 'Food-processing grade', 'Competitive interstate supply'],
    note: 'Bulk pearl millet for food processors, flour mills, institutional kitchens, and distributors.',
  },
  {
    id: 'cardamom-kerala',
    sellerId: 'seller-3',
    corridorId: 'kerala-india',
    productClass: 'plant',
    name: 'Premium green cardamom',
    category: 'Spices',
    state: 'Kerala',
    origin: 'Idukki verified grower aggregation',
    imageUrl: '/product-images/cardamom.jpg',
    unit: '120 kg wholesale lot',
    basePrice: 336000,
    priceUpdatedAt: '2026-06-26',
    procurementFrequency: 'Fortnightly',
    availableQty: '5 lots this week',
    specs: ['7-8 mm bold grade', 'Low split percentage', 'Moisture-controlled cartons'],
    certifications: ['Spices Board registration', 'FSSAI licence verified', 'Residue test report'],
    decisionFactors: ['Premium aroma retention', 'Strong quality traceability', 'Verified Idukki origin'],
    note: 'Premium spice lots with verified grade, state origin, and quality documents.',
  },
  {
    id: 'coffee-karnataka',
    sellerId: 'seller-4',
    corridorId: 'karnataka-india',
    productClass: 'plant',
    name: 'Robusta coffee beans',
    category: 'Coffee',
    state: 'Karnataka',
    origin: 'Chikkamagaluru coffee grower cluster',
    imageUrl: '/product-images/coffee.jpg',
    unit: '2,000 kg wholesale lot',
    basePrice: 408000,
    priceUpdatedAt: '2026-06-23',
    procurementFrequency: 'Monthly',
    availableQty: '4 lots this week',
    specs: ['Screen 16', 'Moisture 11-12%', 'Jute bags with food-grade liner'],
    certifications: ['Coffee Board registration', 'Quality inspection report', 'GCTC supplier verification'],
    decisionFactors: ['Consistent blending grade', 'Scalable domestic supply', 'Traceable Karnataka origin'],
    note: 'Reliable bulk coffee input for roasters, beverage manufacturers, and institutional buyers.',
  },
]

export const sellerSaleSeeds: SellerSaleSeed[] = [
  {
    id: 'SALE-2048',
    sellerId: 'seller-1',
    productId: 'cashew-maharashtra',
    buyerAlias: 'Buyer account DL-184',
    soldAt: '2026-06-24',
    lots: 3,
    quantityTons: 1.5,
    amount: 1386000,
    fulfilment: 'turnkey',
    qualityStatus: 'passed',
    disputeCount: 0,
  },
  {
    id: 'SALE-2036',
    sellerId: 'seller-1',
    productId: 'cocoa-andhra',
    buyerAlias: 'Buyer account MH-092',
    soldAt: '2026-06-17',
    lots: 2,
    quantityTons: 2,
    amount: 636000,
    fulfilment: 'sourcing-only',
    qualityStatus: 'passed',
    disputeCount: 0,
  },
  {
    id: 'SALE-2019',
    sellerId: 'seller-1',
    productId: 'sesame-gujarat',
    buyerAlias: 'Buyer account KA-241',
    soldAt: '2026-06-05',
    lots: 1,
    quantityTons: 2,
    amount: 286000,
    fulfilment: 'turnkey',
    qualityStatus: 'review',
    disputeCount: 1,
  },
  {
    id: 'SALE-1998',
    sellerId: 'seller-2',
    productId: 'turmeric-telangana',
    buyerAlias: 'Buyer account TN-033',
    soldAt: '2026-05-28',
    lots: 4,
    quantityTons: 2,
    amount: 740000,
    fulfilment: 'turnkey',
    qualityStatus: 'passed',
    disputeCount: 0,
  },
]

export const logisticsPartnerSeeds: LogisticsPartnerSeed[] = [
  {
    id: 'LOG-WH-014',
    type: 'Warehouse',
    legalName: 'Harbourline Storage Private Limited',
    corridor: 'Mumbai, Maharashtra',
    baseRatePerTon: 1450,
    distanceRatePerTonKm: 0,
    capacity: '2,400 tons',
    status: 'Verified',
    lastAudit: '2026-05-12',
  },
  {
    id: 'LOG-TR-027',
    type: 'Truck',
    legalName: 'Western Freight Carriers',
    corridor: 'Maharashtra, Gujarat, and Rajasthan',
    baseRatePerTon: 900,
    distanceRatePerTonKm: 4.2,
    capacity: '18 trucks',
    status: 'Verified',
    lastAudit: '2026-04-22',
  },
  {
    id: 'LOG-CT-009',
    type: 'Container trailer',
    legalName: 'Interstate Trailer Services',
    corridor: 'West and South India',
    baseRatePerTon: 1250,
    distanceRatePerTonKm: 5.1,
    capacity: '12 trailers',
    status: 'Review due',
    lastAudit: '2025-12-18',
  },
  {
    id: 'LOG-PM-031',
    type: 'Packing and movers',
    legalName: 'CargoCare Handling LLP',
    corridor: 'Pan India',
    baseRatePerTon: 2200,
    distanceRatePerTonKm: 1.3,
    capacity: '32 crews',
    status: 'Verified',
    lastAudit: '2026-05-30',
  },
  {
    id: 'LOG-LD-044',
    type: 'Local delivery',
    legalName: 'CityDock Delivery Network',
    corridor: 'Delhi NCR, Mumbai MMR, Bengaluru, and Chennai',
    baseRatePerTon: 700,
    distanceRatePerTonKm: 3.8,
    capacity: 'Same-day under 8 tons',
    status: 'Verified',
    lastAudit: '2026-06-03',
  },
]
