# Generated by Django 5.1.15 on 2026-07-05 16:59

import django.db.models.deletion
import trade.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('admin', 'Admin')], max_length=10)),
                ('organization', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', trade.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsPartner',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=40)),
                ('legal_name', models.CharField(max_length=120)),
                ('corridor', models.CharField(max_length=120)),
                ('base_rate_per_ton', models.IntegerField()),
                ('distance_rate_per_ton_km', models.FloatField()),
                ('capacity', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=20)),
                ('last_audit', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('corridor_id', models.CharField(max_length=40)),
                ('product_class', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=60)),
                ('origin', models.CharField(max_length=160)),
                ('image_url', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=80)),
                ('base_price', models.IntegerField()),
                ('price_version', models.IntegerField(default=1)),
                ('price_updated_at', models.DateField()),
                ('procurement_frequency', models.CharField(max_length=40)),
                ('available_qty', models.CharField(max_length=60)),
                ('specs', models.JSONField(default=list)),
                ('certifications', models.JSONField(default=list)),
                ('decision_factors', models.JSONField(default=list)),
                ('note', models.TextField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=40)),
                ('previous_price', models.IntegerField()),
                ('new_price', models.IntegerField()),
                ('reason', models.CharField(max_length=120)),
                ('effective_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_revisions', to='trade.product')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lots', models.IntegerField()),
                ('freight_tier', models.CharField(max_length=10)),
                ('mover_tier', models.CharField(max_length=10)),
                ('fulfilment', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=8)),
                ('totals', models.JSONField()),
                ('total_amount', models.FloatField()),
                ('rule_pack_version', models.IntegerField()),
                ('price_version', models.IntegerField()),
                ('status', models.CharField(default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='trade.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('seller_id', models.CharField(max_length=40)),
                ('lots', models.IntegerField()),
                ('fulfilment', models.CharField(max_length=20)),
                ('freight_tier', models.CharField(max_length=10)),
                ('mover_tier', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=8)),
                ('totals', models.JSONField()),
                ('total_amount', models.FloatField()),
                ('status', models.CharField(max_length=60)),
                ('payment_status', models.CharField(max_length=20)),
                ('corridor_label', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='trade.product')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='trade.quote')),
            ],
        ),
        migrations.CreateModel(
            name='SellerSale',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('seller_id', models.CharField(max_length=40)),
                ('buyer_alias', models.CharField(max_length=80)),
                ('sold_at', models.DateField()),
                ('lots', models.IntegerField()),
                ('quantity_tons', models.FloatField()),
                ('amount', models.IntegerField()),
                ('fulfilment', models.CharField(max_length=20)),
                ('quality_status', models.CharField(max_length=12)),
                ('dispute_count', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='trade.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller'], name='trade_produ_seller__7384ab_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='trade_produ_categor_26a576_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['state'], name='trade_produ_state_290f7c_idx'),
        ),
        migrations.AddIndex(
            model_name='pricerevision',
            index=models.Index(fields=['seller_id', '-effective_at'], name='trade_price_seller__515bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['buyer', '-created_at'], name='trade_quote_buyer_i_ff306d_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['product', 'status'], name='trade_quote_product_f9097d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', '-created_at'], name='trade_order_buyer_i_61ed81_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['seller_id', '-created_at'], name='trade_order_seller__eef4e0_idx'),
        ),
        migrations.AddIndex(
            model_name='sellersale',
            index=models.Index(fields=['seller_id', '-sold_at'], name='trade_selle_seller__cb27ff_idx'),
        ),
    ]
